### ISSUE TITLE
Whisper large v3 Inference

### ISSUE THREAD

**Issue by Jain-Archit** [yuekaizhang/Triton-ASR-Client#3]
Hi @yuekaizhang , 

I am trying to host whisper large v3 on Nvidia Triton Inference Server. I saw that you have converted large v2 model to onnx. I am trying to achieve the same with large v3. Can you help and share the conversion script used for converting? Also, if there is anything else which may change for large-v3 model?

**Comment by yuekaizhang** [comment]
See this https://github.com/k2-fsa/sherpa/tree/master/triton/whisper for convert scripts. You may change input feature dim from 80 to 128 for whisper large v3.
