### ISSUE TITLE
请问如何传递return_timestamps（True或'word'）、task和language参数呢

### ISSUE THREAD

**Issue by Wyswyss** [yuekaizhang/Triton-ASR-Client#4]
如题，因为在使用的时候时间戳对我来说很关键，请问triton client是否支持呢？非常感谢！

**Comment by yuekaizhang** [comment]
> 如题，因为在使用的时候时间戳对我来说很关键，请问triton client是否支持呢？非常感谢！

@Wyswyss https://github.com/yuekaizhang/Triton-ASR-Client/blob/main/client.py#L78 修改这里即可，比如 <translation>、<en>

**Comment by Wyswyss** [comment]
> > 如题，因为在使用的时候时间戳对我来说很关键，请问triton client是否支持呢？非常感谢！
> 
> @Wyswyss https://github.com/yuekaizhang/Triton-ASR-Client/blob/main/client.py#L78 修改这里即可，比如 <|translation|>、<|en|>

好的，多谢！
