### ISSUE TITLE
run sensevoice model lose punctuation

### ISSUE THREAD

**Issue by XiaYucca** [yuekaizhang/Triton-ASR-Client#5]
Using FunASR/runtime
/Triton-gpu runs the sense model as the backend, but why do all recognition results lose punctuation?

**Comment by yuekaizhang** [comment]
> Using FunASR/runtime /Triton-gpu runs the sense model as the backend, but why do all recognition results lose punctuation?

https://github.com/yuekaizhang/Triton-ASR-Client/blob/main/client.py#L401-402 Set the text_norm according to the Sensevoice docs please.

**Comment by XiaYucca** [comment]
> > Using FunASR/runtime /Triton-gpu runs the sense model as the backend, but why do all recognition results lose punctuation?
> 
> https://github.com/yuekaizhang/Triton-ASR-Client/blob/main/client.py#L401-402 Set the text_norm according to the Sensevoice docs please.

Great, I found the value {"withitn": 14, "woitn": 15} and it works fine, thanks!
